runtime: nodejs18
instance_class: F1

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

env_variables:
 DATABASE_URL: mongodb+srv://admin:0BCPpzU2q6oh2fgg@cluster0.wzhpbnh.mongodb.net/noteit?retryWrites=true&w=majority